name:                creative-approval-service
version:             0.1.0.0
github:              "gitlab.cortb.pl/creative-approval-service"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 CoRTB"

extra-source-files:
- README.md
- ChangeLog.md


description:        Creative Service to add creatives to SSP and auditing them.

ghc-options:
- -fplugin=Polysemy.Plugin

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
- aeson
- aeson-casing
- base >= 4.7 && < 5
- containers
- unordered-containers
- time
- iso8601-time
- polysemy
- polysemy-plugin
- errors
- uuid
- time
- bytestring
- text
- text-show
- lens
- req >= 3.1.0
- configurator
- mtl
- http-client
- http-client-tls
- connection
- retry
- co-log-core
- timers
- modern-uri

library:
  source-dirs: src

executables:

  reative-approval-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - creative-approval-service

tests:
  creative-approval-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - creative-approval-service
